name: Archive PyTorch wheel

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PyTorch version (e.g. 2.7.0.dev20250208)'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel
        run: |
          wget -q https://download.pytorch.org/whl/nightly/cu126/torch-${{ github.event.inputs.version }}%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          files: torch-*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
